/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ZList_constants.h"

namespace zingme { namespace zlist { namespace thrift { namespace cpp2 {

}}}} // zingme::zlist::thrift::cpp2