/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#pragma once

#include "ZList_types.h"
#include <thrift/lib/cpp2/protocol/Protocol.h>
namespace zingme { namespace zlist { namespace thrift { namespace cpp2 {

struct ZList_constants {};

class __attribute__((__deprecated__("ZListConstants suffers from the 'static initialization order fiasco' (https://isocpp.org/wiki/faq/ctors#static-init-order) and may CRASH you program. Instead, use ZList_constants::CONSTANT_NAME()"))) ZListConstants {
 public:
  ZListConstants() {}
};

}}}} // zingme::zlist::thrift::cpp2